export const lookingRoom = [{
  gender: 'Male',
  startingDate: "2018-11-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '400-500 EUR',
  location: 'Amsterdam',
  description: "Hi, my name is Slava. I'm 32 years old. I'm looking for a room. I'd like sports and active lifestyle.",
  image: 'http://www.popstaronline.com/wp-content/uploads/2018/07/Game-of-Thrones-4-400x400.jpg',
  login: 'Slava',
  password: '1234',
  mobile: "+79271334562",
  email: "slavakingofthenorth@gmail.ru",
  wantToMatch: true
},
{
  gender: 'Male',
  startingDate: "2018-11-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '400-500 EUR',
  location: 'Amsterdam',
  description: "Hi, my name is Petr. I'm 30 years old. I am looking for a room. I'd like loud music and noisy companies.",
  image: 'http://www.thelegendarytrend.com/wp-content/uploads/2016/02/LeonardoDiCaprio10-400x400.jpg',
  login: 'Petr',
  password: '1235',
  mobile: "+79191334562",
  email: "ilikehorses@ya.ru",
  wantToMatch: true
},
{
  gender: 'Male',
  startingDate: "2018-11-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '400-500 EUR',
  location: 'Amsterdam',
  description: "Hi, my name is Stepan. I'm 27 years old. I'm looking for a room. I'd like delicious food and sleep all day.",
  image: 'http://www.popstaronline.com/wp-content/uploads/2018/06/chris-pratt-time-100-2015-artists-1-400x400.jpg',
  login: 'Stepan',
  password: '1734',
  mobile: "+79871337562",
  email: "dinotamer@ya.ru",
  wantToMatch: true
},
{
  gender: 'Female',
  startingDate: "2018-11-09",
  pets: 'Yes',
  smoking: 'No',
  price: '500-600 EUR',
  location: 'Amsterdam',
  description: "Hi, my name is Sveta. I'm 23 years old. I am looking for a room. I have a fluffy cat, that constantly sheeds.",
  image: 'http://www.popstaronline.com/wp-content/uploads/2018/09/Kristen-Bell-Thumbnail-400x400.jpg',
  login: 'Sveta',
  password: '0123',
  mobile: "+79667893465",
  email: "exwife@ya.ru",
  wantToMatch: true
},
{
  gender: 'Male',
  startingDate: "2018-06-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '700-800 EUR',
  location: 'Amsterdam',
  description: "Hi, my name is Viktor. I am 37 years old. I'm looking for a room. 'Sex, drugs and rock & roll' - it's about me.",
  image: 'http://saranossaterra.com.br/content/uploads/2015/12/brad-pitt_416x416-400x400.jpg',
  login: 'Vikor',
  password: '5678',
  mobile: "+7927657854",
  email: "misterblack@mail.ru",
  wantToMatch: true
},
{
  gender: 'Female',
  startingDate: "2018-01-08",
  pets: 'No',
  smoking: 'No',
  price: '400-500 EUR',
  location: 'Amsterdam',
  description: "Hi, my name is Vika. I'm 37 years old. I'm looking for a room. I'd like reeding, cooking and knitting. I have alergy by cats.",
  image: 'https://www.thisblogrules.com/wp-content/uploads/2015/01/081308_adams_400x400.jpg',
  login: 'Vika',
  password: '1357',
  mobile: "+79331337562",
  email: "veronikamars@rambler.ru",
  wantToMatch: true
}
]





export const offerRoom = [{
  gender: 'male',
  startingDate: "2018-11-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '400-500 EUR',
  location: 'Amsterdam',
  description: "I'm loking for a roommate. In apartment has a fridge, washing machine and funny cat.",
  image: 'http://lousescartoun.com/wp-content/uploads/2017/06/Camera-Jusfine-38-400x400-c-default.jpg',
  login: 'Oleg',
  password: '1230',
  mobile: "+79331337562",
  email: "bigbier@yandex.ru",
  wantToMatch: true
},
{
  gender: 'Female',
  startingDate: "2018-11-09",
  pets: 'Yes',
  smoking: 'No',
  price: '500-600 EUR',
  location: 'Amsterdam',
  description: "I'm loking for a roommate. Bright, clean room on the outskirts of the Amsterdam.",
  image:'https://sandbergwallpaper.com/wp-content/uploads//433-88_3-1-400x400.jpg',
  login: 'Olga',
  password: '1272',
  mobile: "+7927657854",
  email: "bigboss@mail.ru",
  wantToMatch: true,
},
{
  gender: 'male',
  startingDate: "2018-12-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '700-800 EUR',
  location: 'Amsterdam',
  description: "I'm loking for a roommate. Unfurnished but with a beautiful wiew ifrom the window.",
  image: 'https://multimedia.3m.com/mws/media/1216793P/3m-window-film.jpg',
  login: 'Artur',
  password: '0000',
  mobile: "+79331337562",
  email: "bigbier@yandex.ru",
  wantToMatch: true,
  
},
{
  gender: 'Female',
  startingDate: "2018-10-08",
  pets: 'No',
  smoking: 'No',
  price: 'under 400 EUR',
  location: 'Amsterdam',
  description: "I'm loking for a roommate. Very cheap.",
  image: 'http://www.vincenzo.gr/wp-content/uploads/2017/01/IMG_5388-400x400.jpg',
  login: 'Liza',
  password: '1233',
  mobile: "+79182345678",
  email: "ladytonight@mail.ru",
  wantToMatch: true,

},
{
  gender: 'Any',
  startingDate: "2018-11-08",
  pets: 'Yes',
  smoking: 'Yes',
  price: '600-700 EUR',
  location: 'Amsterdam',
  description: "I'm loking for a roommate. Fully furnished. Apartment on te 22nd floor. No elevator.",
  image: 'https://ydom43.ru/uploads/room/400x400/room_3_5b040401c7fd9.jpeg',
  login: 'Igor',
  password: '2234',
  mobile: "+79100345678",
  email: "bluelaguna2018@mail.ru",
  wantToMatch: true,
},
]